SELECT
    data:context:results:sketchy_details:username::VARCHAR AS username,
    data:datetime::TIMESTAMP_NTZ AS event_timestamp,
    '{{ ds }}'::DATE AS date_utc,
    data:context:results:sketchy_details:client_type::VARCHAR AS client_type,
    data:context:results:sketchy_details:client_version::VARCHAR AS client_version,
    data:context:results:sketchy_details:ip_address::VARCHAR AS ip_address,
    data:context:results:sketchy_details:ip_country::VARCHAR AS ip_country,
    data:context:results:sketchy_details:ip_timezone::VARCHAR AS ip_timezone,
    data:context:results:sketchy_details:android_id::VARCHAR AS android_id,
    data:context:results:sketchy_details:gps_adid::VARCHAR AS gps_adid,
    data:context:results:sketchy_details:idfa::VARCHAR AS idfa,
    data:context:results:sketchy_details:idfv::VARCHAR AS idfv,
    data:context:results:sketchy_details:password_sha256::VARCHAR AS password_sha256,
    data:context:results:sketchy_details:user_agent::VARCHAR AS user_agent,
    data:context:results:sketchy_details:device_timezone::VARCHAR AS device_timezone,
    data:context:results:sketchy_details:bonus:Board::VARCHAR AS "bonus.Board",
    data:context:results:sketchy_details:bonus:Brand::VARCHAR AS "bonus.Brand",
    data:context:results:sketchy_details:bonus:Bootloader::VARCHAR AS "bonus.Bootloader",
    data:context:results:sketchy_details:bonus:CarrierCountry::VARCHAR AS "bonus.CarrierCountry",
    data:context:results:sketchy_details:bonus:CarrierName::VARCHAR AS "bonus.CarrierName",
    data:context:results:sketchy_details:bonus:CarrierISOCountryCode::VARCHAR AS "bonus.CarrierISOCountryCode",
    data:context:results:sketchy_details:bonus:CarrierMobileCountryCode::VARCHAR AS "bonus.CarrierMobileCountryCode",
    data:context:results:sketchy_details:bonus:CarrierMobileNetworkCode::VARCHAR AS "bonus.CarrierMobileNetworkCode",
    data:context:results:sketchy_details:bonus:ConnectedToCellNetwork::VARCHAR AS "bonus.ConnectedToCellNetwork",
    data:context:results:sketchy_details:bonus:ConnectedToWiFi::VARCHAR AS "bonus.ConnectedToWiFi",
    data:context:results:sketchy_details:bonus:Country::VARCHAR AS "bonus.Country",
    data:context:results:sketchy_details:bonus:Currency::VARCHAR AS "bonus.Currency",
    data:context:results:sketchy_details:bonus:DeviceModel::VARCHAR AS "bonus.DeviceModel",
    data:context:results:sketchy_details:bonus:DeviceName::VARCHAR AS "bonus.DeviceName",
    data:context:results:sketchy_details:bonus:Jailbroken::VARCHAR AS "bonus.Jailbroken",
    data:context:results:sketchy_details:bonus:Device::VARCHAR AS "bonus.Device",
    data:context:results:sketchy_details:bonus:Language::VARCHAR AS "bonus.Language",
    data:context:results:sketchy_details:bonus:Fingerprint::VARCHAR AS "bonus.Fingerprint",
    data:context:results:sketchy_details:bonus:Manufacturer::VARCHAR AS "bonus.Manufacturer",
    data:context:results:sketchy_details:bonus:Model::VARCHAR AS "bonus.Model",
    data:context:results:sketchy_details:bonus:Product::VARCHAR AS "bonus.Product",
    data:context:results:sketchy_details:bonus:RadioVersion::VARCHAR AS "bonus.RadioVersion",
    data:context:results:sketchy_details:bonus:ScreenBrightness::VARCHAR AS "bonus.ScreenBrightness",
    data:context:results:sketchy_details:bonus:ScreenHeight::VARCHAR AS "bonus.ScreenHeight",
    data:context:results:sketchy_details:bonus:ScreenWidth::VARCHAR AS "bonus.ScreenWidth",
    data:context:results:sketchy_details:bonus:SystemDeviceType::VARCHAR AS "bonus.SystemDeviceType",
    data:context:results:sketchy_details:bonus:SystemVersion::VARCHAR AS "bonus.SystemVersion",
    data:context:results:sketchy_details:bonus:WiFiIPAddress::VARCHAR AS "bonus.WiFiIPAddress",
    data:context:results:sketchy_details:bonus:WiFiRouterAddress::VARCHAR AS "bonus.WiFiRouterAddress",
    REPLACE(data:context:results:action, '"', '') AS action,
    REPLACE(data:context:results:original_action, '"', '') AS original_action,
    data:context:results:registrationCaptchaOrBlock:sketchy_level::INT AS "registration_captcha_block.sketchy_level",
    data:context:results:registrationCaptchaOrBlock:sketchy_results:EmailAddressSMTPValidatorPlugin:message::VARCHAR AS "registration_captcha_block.sketchy_results.EmailAddressSMTPValidatorPlugin.message",
    data:context:results:registrationCaptchaOrBlock:sketchy_results:IntegrityAttestationPlugin:message::VARCHAR AS "registration_captcha_block.sketchy_results.IntegrityAttestationPlugin.message",
    data:context:results:registrationCaptchaOrBlock:sketchy_results:IpInfoPlugin:intermediate:ip_info_behaviours::VARCHAR AS "registration_captcha_block.sketchy_results.IpInfoPlugin.intermediate.ip_info_behaviours",
    data:context:results:registrationCaptchaOrBlock:sketchy_results:RegistrationTimezonePlugin:intermediate:deviceTimezoneOffset::INT AS "registration_captcha_block.sketchy_results.RegistrationTimezonePlugin.intermediate.deviceTimezoneOffset",
    data:context:results:registrationCaptchaOrBlock:sketchy_results:RegistrationTimezonePlugin:intermediate:ipTimezoneOffset::INT AS "registration_captcha_block.sketchy_results.RegistrationTimezonePlugin.intermediate.ipTimezoneOffset",
    data:context:results:registrationCaptchaOrBlock:sketchy_results:SequentialUsernamePlugin:intermediate:decimal::INT AS "registration_captcha_block.sketchy_results.SequentialUsernamePlugin.intermediate.decimal",
    data:context:results:registrationCaptchaOrAllow:sketchy_level::INT AS "registration_captcha_allow.sketchy_level",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:MultipleRegistrationsFromSingleIpAddressPlugin:intermediate:registerCount::INT AS "registration_captcha_allow.MultipleRegistrationsFromSingleIpAddressPlugin.intermediate.registerCount",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:MultipleRegistrationsFromSingleIpAddressPlugin:message::VARCHAR AS "registration_captcha_allow.MultipleRegistrationsFromSingleIpAddressPlugin.message",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:MultipleRegistrationsFromSingleIpAddressPlugin:tripped::BOOLEAN AS "registration_captcha_allow.MultipleRegistrationsFromSingleIpAddressPlugin.tripped",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:MultipleRegistrationsFromSingleIpAddressPlugin:weight::INT AS "registration_captcha_allow.MultipleRegistrationsFromSingleIpAddressPlugin.weight",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:RegistrationTimezonePlugin:intermediate:deviceTimezoneOffset::INT AS "registration_captcha_allow.RegistrationTimezonePlugin.intermediate.deviceTimezoneOffset",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:RegistrationTimezonePlugin:intermediate:ipTimezoneOffset::INT AS "registration_captcha_allow.RegistrationTimezonePlugin.intermediate.ipTimezoneOffset",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:RegistrationTimezonePlugin:tripped::BOOLEAN AS "registration_captcha_allow.RegistrationTimezonePlugin.tripped",
    data:context:results:registrationCaptchaOrAllow:sketchy_results:RegistrationTimezonePlugin:weight::INT AS "registration_captcha_allow.RegistrationTimezonePlugin.weight",
    data:context:results:sketchy_details AS sketchy_details,
    data:context:results:registrationCaptchaOrBlock AS registration_captcha_block,
    data:context:results:registrationCaptchaOrAllow AS registration_captcha_allow,
    '{{ data_interval_start }}' AS source_file_time,
    SYSDATE() AS inserted_at
FROM staging
WHERE (sketchy_details:sketchy_context = 'registration')
