{{
    config(
        tags=['daily'],
        materialized='table',
        unique_key='charge_id'
    )
}}

WITH billing_service AS (
    SELECT  receipt_item_id AS charge_id,
            receipt_id,
            invoice_id,
            username,
            created_at,
            updated_at,
            receipt_category,
            payment_provider,
            identifier,
            payment_method,
            NVL(receipt_item_amount, 0) AS charge_amount
    FROM {{ ref('billing_service_receipt_items') }}
    WHERE receipt_category = 'capture'
      AND invoice_state = 'closed'
),
stripe AS (
    SELECT  stripe_charge_id as charge_id,
            stripe_charge_id AS receipt_id,
            stripe_charge_id AS invoice_id,
            username,
            created_at,
            updated_at,
            category As receipt_category,
            payment_provider,
            identifier,
            payment_method,
            NVL(amount, 0) AS charge_amount
    FROM {{ ref('stripe_charges') }}
    WHERE receipt_id IS NULL  -- a non-null charges_stripe.receipt_id implies that it was generated by Billing Service
      AND stripe_charge_id NOT IN (
        SELECT identifier
        FROM {{ ref('billing_service_receipt_items') }}
        WHERE payment_provider ILIKE 'Stripe%'
          AND identifier IS NOT NULL
        )
      /*
        Even if we have more data from Stripe, we don't to go beyond the latest row in billing_service_receipt_items
      */
      AND updated_at <= (SELECT MAX(updated_at) FROM {{ ref('billing_service_receipt_items') }})
),
braintree AS (
    SELECT  braintree_charge_id as charge_id,
            braintree_charge_id AS receipt_id,
            braintree_charge_id AS invoice_id,
            NULL AS username,
            created_at,
            updated_at,
            category As receipt_category,
            payment_provider,
            identifier,
            NULL AS payment_method,
            NVL(amount, 0) As charge_amount
    FROM {{ ref('braintree_charges') }}
    WHERE braintree_charge_id NOT IN (
        SELECT identifier
        FROM {{ ref('billing_service_receipt_items') }}
        WHERE payment_provider ILIKE '%Braintree%'
          AND identifier IS NOT NULL
        )
      /*
        Even if we have more data from Braintree, we don't to go beyond the latest row in billing_service_receipt_items
      */
      AND updated_at <= (SELECT MAX(updated_at) FROM {{ ref('billing_service_receipt_items') }})
)
SELECT * FROM billing_service

UNION ALL  -- add in Stripe data if billing service doesn't have it

SELECT * FROM stripe

UNION ALL  -- add in braintree data if billing service doesn't have it

SELECT * FROM braintree