{{
    config(
        tags=['daily'],
        materialized='view',
    )
}}

-- Note: we are filtering for only 6 months on this View to keep the performance under control
--       there are no downstream usages here

SELECT
    date_utc,
    "client_details.android_bonus_data.android_id",
    "client_details.android_bonus_data.adjust_id",
    "client_details.android_bonus_data.firebase_id",
    "client_details.android_bonus_data.google_analytics_unique_id",
    "client_details.android_bonus_data.battery_level",
    "client_details.android_bonus_data.bluetooth_mac_address",
    "client_details.android_bonus_data.board_name",
    "client_details.android_bonus_data.bootloader_version",
    "client_details.android_bonus_data.brand_name",
    "client_details.android_bonus_data.build_fingerprint",
    "client_details.android_bonus_data.build_id",
    "client_details.android_bonus_data.device_id",
    "client_details.android_bonus_data.device_name",
    "client_details.android_bonus_data.google_play_services_advertising_id",
    "client_details.android_bonus_data.hardware_name",
    "client_details.android_bonus_data.iccid",
    "client_details.android_bonus_data.is_user_a_monkey",
    "client_details.android_bonus_data.manufacturer_name",
    "client_details.android_bonus_data.model_name",
    "client_details.android_bonus_data.os_base",
    "client_details.android_bonus_data.os_codename",
    "client_details.android_bonus_data.os_version",
    "client_details.android_bonus_data.product_name",
    "client_details.android_bonus_data.radio_version",
    "client_details.android_bonus_data.screen_height",
    "client_details.android_bonus_data.screen_width",
    "client_details.android_bonus_data.sdk_version",
    "client_details.android_bonus_data.uptime",
    "client_details.android_bonus_data.wifi_mac_address",

    "client_details.client_data.brand",
    "client_details.client_data.client_ip_address",
    "client_details.client_data.client_platform",
    "client_details.client_data.client_port",
    "client_details.client_data.client_version",
    "client_details.client_data.country_code",
    "client_details.client_data.language_code",
    "client_details.client_data.client_calling_sdk_version",
    "client_details.client_data.tz_code",
    "client_details.client_data.user_agent",
    "client_details.client_data.user_data.date_of_birth",
    "client_details.client_data.user_data.email",
    "client_details.client_data.user_data.email_status",
    "client_details.client_data.user_data.first_name",
    "client_details.client_data.user_data.last_name",
    "client_details.client_data.user_data.username",

    "client_details.ios_bonus_data.idfa",
    "client_details.ios_bonus_data.idfv",
    "client_details.ios_bonus_data.adjust_id",
    "client_details.ios_bonus_data.model_name",
    "client_details.ios_bonus_data.os_version",
    "client_details.ios_bonus_data.product_name",
    "client_details.ios_bonus_data.screen_height",
    "client_details.ios_bonus_data.screen_width",

    create_time_server_offset,
    created_at,
    event_id,
    instance_id,
    proto_class,
    user_id,
    user_id_hex,

    "payload.ad_event_data.ad_unit_id",
    "payload.ad_event_data.advertisement.creative_id",
    "payload.ad_event_data.advertisement.format",
    "payload.ad_event_data.advertisement.size.height",
    "payload.ad_event_data.advertisement.size.width",
    "payload.ad_event_data.experiment_id",
    "payload.ad_event_data.experiment_name",
    "payload.ad_event_data.experiment_variant",
    "payload.ad_event_data.keywords",
    "payload.ad_event_data.network",
    "payload.ad_event_data.placement",
    "payload.ad_event_data.ppid",
    "payload.ad_event_data.request_id",
    "payload.ad_event_data.request_type",
    "payload.ad_event_data.screen",
    "payload.ad_event_data.ad_report_kvs.best_gender",
    "payload.ad_event_data.ad_report_kvs.pixalate_fraud_type",
    "payload.ad_event_data.ad_report_kvs.pixalate_probability",
    "payload.ad_event_data.ad_report_kvs.strategic_seg",
    inserted_timestamp,
    s3_file_path
FROM {{ source('party_planner_realtime', 'ad_click') }}
WHERE date_utc >= {{ var('ds') }}::DATE - INTERVAL '183 days'

UNION ALL SELECT
    date_utc,
    "client_details.android_bonus_data.android_id",
    "client_details.android_bonus_data.adjust_id",
    "client_details.android_bonus_data.firebase_id",
    "client_details.android_bonus_data.google_analytics_unique_id",
    "client_details.android_bonus_data.battery_level",
    "client_details.android_bonus_data.bluetooth_mac_address",
    "client_details.android_bonus_data.board_name",
    "client_details.android_bonus_data.bootloader_version",
    "client_details.android_bonus_data.brand_name",
    "client_details.android_bonus_data.build_fingerprint",
    "client_details.android_bonus_data.build_id",
    "client_details.android_bonus_data.device_id",
    "client_details.android_bonus_data.device_name",
    "client_details.android_bonus_data.google_play_services_advertising_id",
    "client_details.android_bonus_data.hardware_name",
    "client_details.android_bonus_data.iccid",
    "client_details.android_bonus_data.is_user_a_monkey",
    "client_details.android_bonus_data.manufacturer_name",
    "client_details.android_bonus_data.model_name",
    "client_details.android_bonus_data.os_base",
    "client_details.android_bonus_data.os_codename",
    "client_details.android_bonus_data.os_version",
    "client_details.android_bonus_data.product_name",
    "client_details.android_bonus_data.radio_version",
    "client_details.android_bonus_data.screen_height",
    "client_details.android_bonus_data.screen_width",
    "client_details.android_bonus_data.sdk_version",
    "client_details.android_bonus_data.uptime",
    "client_details.android_bonus_data.wifi_mac_address",

    "client_details.client_data.brand",
    "client_details.client_data.client_ip_address",
    "client_details.client_data.client_platform",
    "client_details.client_data.client_port",
    "client_details.client_data.client_version",
    "client_details.client_data.country_code",
    "client_details.client_data.language_code",
    "client_details.client_data.client_calling_sdk_version",
    "client_details.client_data.tz_code",
    "client_details.client_data.user_agent",
    "client_details.client_data.user_data.date_of_birth",
    "client_details.client_data.user_data.email",
    "client_details.client_data.user_data.email_status",
    "client_details.client_data.user_data.first_name",
    "client_details.client_data.user_data.last_name",
    "client_details.client_data.user_data.username",

    "client_details.ios_bonus_data.idfa",
    "client_details.ios_bonus_data.idfv",
    "client_details.ios_bonus_data.adjust_id",
    "client_details.ios_bonus_data.model_name",
    "client_details.ios_bonus_data.os_version",
    "client_details.ios_bonus_data.product_name",
    "client_details.ios_bonus_data.screen_height",
    "client_details.ios_bonus_data.screen_width",

    create_time_server_offset,
    created_at,
    event_id,
    instance_id,
    proto_class,
    user_id,
    user_id_hex,

    "payload.impression.ad_unit_id" AS "payload.ad_event_data.ad_unit_id",
    "payload.impression.advertisement.creative_id" AS "payload.ad_event_data.advertisement.creative_id",
    "payload.impression.advertisement.format" AS "payload.advertisement.format",
    "payload.impression.advertisement.size.height" AS "payload.ad_event_data.advertisement.size.height",
    "payload.impression.advertisement.size.width" AS "payload.ad_event_data.advertisement.size.width",
    NULL AS "payload.ad_event_data.experiment_id",
    NULL AS "payload.ad_event_data.experiment_name",
    NULL AS "payload.ad_event_data.experiment_variant",
    NULL AS "payload.ad_event_data.keywords",
    "payload.impression.network" AS "payload.ad_event_data.network",
    "payload.impression.placement" AS "payload.ad_event_data.placement",
    NULL AS "payload.ad_event_data.ppid",
    NULL AS "payload.ad_event_data.request_id",
    "payload.impression.request_type" AS "payload.ad_event_data.request_type",
    "payload.impression.screen" AS "payload.ad_event_data.screen",
    NULL AS "payload.ad_event_data.ad_report_kvs.best_gender",
    NULL AS "payload.ad_event_data.ad_report_kvs.pixalate_fraud_type",
    NULL AS "payload.ad_event_data.ad_report_kvs.pixalate_probability",
    NULL AS "payload.ad_event_data.ad_report_kvs.strategic_seg",
    inserted_timestamp,
    s3_file_path
FROM {{ source('party_planner_realtime', 'click') }}
WHERE date_utc >= {{ var('ds') }}::DATE - INTERVAL '183 days'
